FROM dockcross/linux-x64

RUN git clone https://github.com/protocolbuffers/protobuf.git
RUN cd protobuf && \
    git submodule update --init --recursive && \
    ./autogen.sh && \
    ./configure && \
    make -j8 && \
    make check -j8 && \
    make install && \
    ldconfig # refresh shared library cache.
